[package]
name = "path_helper"
version = "0.1.0"
edition = "2021"
authors = ["yooyi(i@uuz.io)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
shellexpand = "2.1"
